title: "Mission Bit"
exclude:
  - .c9
  - vendor/bundle
  - vendor/heroku
  - Dockerfile
  - Dockerfile.web
  - docker-compose.yml
  - docker-compose-ci.yml
  - config.ru
  - docker-start.sh
  - docker-ci.sh
  - app.json
  - Gemfile
  - Gemfile.lock
  - heroku.yml
  - Rakefile
  - README.md
  - ci
  - azure-pipelines.yml
  - .travis.yml
  - .editorconfig
  - .gitignore
  - archive
  - default.nix
  - .nix-gems
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
